# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs\gui_fit.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 375)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cbModel = QtWidgets.QComboBox(Dialog)
        self.cbModel.setObjectName("cbModel")
        self.verticalLayout.addWidget(self.cbModel)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.cbMethod = QtWidgets.QComboBox(Dialog)
        self.cbMethod.setObjectName("cbMethod")
        self.verticalLayout.addWidget(self.cbMethod)
        self.cbDisplaResult = QtWidgets.QCheckBox(Dialog)
        self.cbDisplaResult.setObjectName("cbDisplaResult")
        self.verticalLayout.addWidget(self.cbDisplaResult)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFit = QtWidgets.QPushButton(Dialog)
        self.btnFit.setCheckable(False)
        self.btnFit.setChecked(False)
        self.btnFit.setAutoRepeat(False)
        self.btnFit.setAutoDefault(False)
        self.btnFit.setObjectName("btnFit")
        self.horizontalLayout_2.addWidget(self.btnFit)
        self.btnShowLastResult = QtWidgets.QPushButton(Dialog)
        self.btnShowLastResult.setCheckable(False)
        self.btnShowLastResult.setChecked(False)
        self.btnShowLastResult.setAutoRepeat(False)
        self.btnShowLastResult.setAutoDefault(False)
        self.btnShowLastResult.setObjectName("btnShowLastResult")
        self.horizontalLayout_2.addWidget(self.btnShowLastResult)
        self.btnCorrelation = QtWidgets.QPushButton(Dialog)
        self.btnCorrelation.setCheckable(False)
        self.btnCorrelation.setChecked(False)
        self.btnCorrelation.setAutoRepeat(False)
        self.btnCorrelation.setAutoDefault(False)
        self.btnCorrelation.setObjectName("btnCorrelation")
        self.horizontalLayout_2.addWidget(self.btnCorrelation)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setAutoDefault(False)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_2.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Model:"))
        self.label_13.setText(_translate("Dialog", "Minimizing algorithm:"))
        self.cbDisplaResult.setText(_translate("Dialog", "Display result after fit"))
        self.label_10.setText(_translate("Dialog", "Species"))
        self.label_15.setText(_translate("Dialog", "Spectrum"))
        self.label_14.setText(_translate("Dialog", "Visible"))
        self.label_7.setText(_translate("Dialog", "Fixed"))
        self.label_3.setText(_translate("Dialog", "Param"))
        self.label_8.setText(_translate("Dialog", "Error"))
        self.label_6.setText(_translate("Dialog", "Upper\n"
"bound"))
        self.label_4.setText(_translate("Dialog", "Lower\n"
"bound"))
        self.label_5.setText(_translate("Dialog", "<= Value <="))
        self.btnFit.setText(_translate("Dialog", "Fit"))
        self.btnShowLastResult.setText(_translate("Dialog", "Show last\n"
"result"))
        self.btnCorrelation.setText(_translate("Dialog", "Correlation\n"
"analysis"))
        self.btnOK.setText(_translate("Dialog", "Ok"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
