# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs\gui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(618, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(999999, 999999))
        self.gridLayout_7 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tImport = QtWidgets.QWidget()
        self.tImport.setObjectName("tImport")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tImport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tImport)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.general_imp_delimiter = QtWidgets.QLineEdit(self.groupBox)
        self.general_imp_delimiter.setObjectName("general_imp_delimiter")
        self.gridLayout_3.addWidget(self.general_imp_delimiter, 5, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 3, 1, 1)
        self.general_imp_decimal_sep = QtWidgets.QLineEdit(self.groupBox)
        self.general_imp_decimal_sep.setObjectName("general_imp_decimal_sep")
        self.gridLayout_3.addWidget(self.general_imp_decimal_sep, 6, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.dx_imp_delimiter = QtWidgets.QLineEdit(self.groupBox)
        self.dx_imp_delimiter.setObjectName("dx_imp_delimiter")
        self.gridLayout_3.addWidget(self.dx_imp_delimiter, 5, 1, 1, 1)
        self.csv_imp_delimiter = QtWidgets.QLineEdit(self.groupBox)
        self.csv_imp_delimiter.setObjectName("csv_imp_delimiter")
        self.gridLayout_3.addWidget(self.csv_imp_delimiter, 5, 2, 1, 1)
        self.dx_imp_decimal_sep = QtWidgets.QLineEdit(self.groupBox)
        self.dx_imp_decimal_sep.setObjectName("dx_imp_decimal_sep")
        self.gridLayout_3.addWidget(self.dx_imp_decimal_sep, 6, 1, 1, 1)
        self.csv_imp_decimal_sep = QtWidgets.QLineEdit(self.groupBox)
        self.csv_imp_decimal_sep.setObjectName("csv_imp_decimal_sep")
        self.gridLayout_3.addWidget(self.csv_imp_decimal_sep, 6, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dx_import_spectra_name_from_filename = QtWidgets.QRadioButton(self.groupBox_5)
        self.dx_import_spectra_name_from_filename.setObjectName("dx_import_spectra_name_from_filename")
        self.verticalLayout_4.addWidget(self.dx_import_spectra_name_from_filename)
        self.rb_DX_import_from_title = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_DX_import_from_title.setChecked(True)
        self.rb_DX_import_from_title.setObjectName("rb_DX_import_from_title")
        self.verticalLayout_4.addWidget(self.rb_DX_import_from_title)
        self.dx_if_title_is_empty_use_filename = QtWidgets.QCheckBox(self.groupBox_5)
        self.dx_if_title_is_empty_use_filename.setObjectName("dx_if_title_is_empty_use_filename")
        self.verticalLayout_4.addWidget(self.dx_if_title_is_empty_use_filename)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.general_import_spectra_name_from_filename = QtWidgets.QRadioButton(self.groupBox_6)
        self.general_import_spectra_name_from_filename.setObjectName("general_import_spectra_name_from_filename")
        self.verticalLayout_8.addWidget(self.general_import_spectra_name_from_filename)
        self.rb_general_import_from_header = QtWidgets.QRadioButton(self.groupBox_6)
        self.rb_general_import_from_header.setChecked(True)
        self.rb_general_import_from_header.setObjectName("rb_general_import_from_header")
        self.verticalLayout_8.addWidget(self.rb_general_import_from_header)
        self.general_if_header_is_empty_use_filename = QtWidgets.QCheckBox(self.groupBox_6)
        self.general_if_header_is_empty_use_filename.setObjectName("general_if_header_is_empty_use_filename")
        self.verticalLayout_8.addWidget(self.general_if_header_is_empty_use_filename)
        self.gridLayout_15.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.gridLayout_16.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tImport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.excel_imp_as_text = QtWidgets.QCheckBox(self.groupBox_2)
        self.excel_imp_as_text.setObjectName("excel_imp_as_text")
        self.verticalLayout_3.addWidget(self.excel_imp_as_text)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.clip_imp_decimal_sep = QtWidgets.QLineEdit(self.groupBox_2)
        self.clip_imp_decimal_sep.setObjectName("clip_imp_decimal_sep")
        self.gridLayout_4.addWidget(self.clip_imp_decimal_sep, 1, 1, 1, 1)
        self.clip_imp_delimiter = QtWidgets.QLineEdit(self.groupBox_2)
        self.clip_imp_delimiter.setObjectName("clip_imp_delimiter")
        self.gridLayout_4.addWidget(self.clip_imp_delimiter, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tImport, "")
        self.tExport = QtWidgets.QWidget()
        self.tExport.setObjectName("tExport")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tExport)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tExport)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.clip_exp_include_group_name = QtWidgets.QCheckBox(self.groupBox_4)
        self.clip_exp_include_group_name.setObjectName("clip_exp_include_group_name")
        self.verticalLayout_5.addWidget(self.clip_exp_include_group_name)
        self.clip_exp_include_header = QtWidgets.QCheckBox(self.groupBox_4)
        self.clip_exp_include_header.setObjectName("clip_exp_include_header")
        self.verticalLayout_5.addWidget(self.clip_exp_include_header)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 0, 1, 1)
        self.clip_exp_decimal_sep = QtWidgets.QLineEdit(self.groupBox_4)
        self.clip_exp_decimal_sep.setObjectName("clip_exp_decimal_sep")
        self.gridLayout_6.addWidget(self.clip_exp_decimal_sep, 1, 1, 1, 1)
        self.clip_exp_delimiter = QtWidgets.QLineEdit(self.groupBox_4)
        self.clip_exp_delimiter.setObjectName("clip_exp_delimiter")
        self.gridLayout_6.addWidget(self.clip_exp_delimiter, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.gridLayout_12.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tExport)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.files_exp_include_group_name = QtWidgets.QCheckBox(self.groupBox_3)
        self.files_exp_include_group_name.setObjectName("files_exp_include_group_name")
        self.verticalLayout_6.addWidget(self.files_exp_include_group_name)
        self.files_exp_include_header = QtWidgets.QCheckBox(self.groupBox_3)
        self.files_exp_include_header.setObjectName("files_exp_include_header")
        self.verticalLayout_6.addWidget(self.files_exp_include_header)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.general_exp_delimiter = QtWidgets.QLineEdit(self.groupBox_3)
        self.general_exp_delimiter.setObjectName("general_exp_delimiter")
        self.gridLayout_5.addWidget(self.general_exp_delimiter, 1, 2, 1, 1)
        self.general_exp_decimal_sep = QtWidgets.QLineEdit(self.groupBox_3)
        self.general_exp_decimal_sep.setObjectName("general_exp_decimal_sep")
        self.gridLayout_5.addWidget(self.general_exp_decimal_sep, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.csv_exp_decimal_sep = QtWidgets.QLineEdit(self.groupBox_3)
        self.csv_exp_decimal_sep.setObjectName("csv_exp_decimal_sep")
        self.gridLayout_5.addWidget(self.csv_exp_decimal_sep, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.csv_exp_delimiter = QtWidgets.QLineEdit(self.groupBox_3)
        self.csv_exp_delimiter.setObjectName("csv_exp_delimiter")
        self.gridLayout_5.addWidget(self.csv_exp_delimiter, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tExport, "")
        self.tPlotting = QtWidgets.QWidget()
        self.tPlotting.setObjectName("tPlotting")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tPlotting)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.antialiasing = QtWidgets.QCheckBox(self.tPlotting)
        self.antialiasing.setObjectName("antialiasing")
        self.verticalLayout_7.addWidget(self.antialiasing)
        self.show_grid = QtWidgets.QCheckBox(self.tPlotting)
        self.show_grid.setObjectName("show_grid")
        self.verticalLayout_7.addWidget(self.show_grid)
        self.same_color_in_group = QtWidgets.QCheckBox(self.tPlotting)
        self.same_color_in_group.setObjectName("same_color_in_group")
        self.verticalLayout_7.addWidget(self.same_color_in_group)
        self.different_line_style_among_groups = QtWidgets.QCheckBox(self.tPlotting)
        self.different_line_style_among_groups.setObjectName("different_line_style_among_groups")
        self.verticalLayout_7.addWidget(self.different_line_style_among_groups)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.bottom_axis_label = QtWidgets.QLineEdit(self.tPlotting)
        self.bottom_axis_label.setObjectName("bottom_axis_label")
        self.gridLayout_13.addWidget(self.bottom_axis_label, 3, 2, 1, 1)
        self.left_axis_label = QtWidgets.QLineEdit(self.tPlotting)
        self.left_axis_label.setObjectName("left_axis_label")
        self.gridLayout_13.addWidget(self.left_axis_label, 2, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tPlotting)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tPlotting)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tPlotting)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 0, 1, 1)
        self.grid_alpha = QtWidgets.QDoubleSpinBox(self.tPlotting)
        self.grid_alpha.setDecimals(2)
        self.grid_alpha.setMaximum(1.0)
        self.grid_alpha.setSingleStep(0.01)
        self.grid_alpha.setObjectName("grid_alpha")
        self.gridLayout_13.addWidget(self.grid_alpha, 0, 2, 1, 1)
        self.graph_title = QtWidgets.QLineEdit(self.tPlotting)
        self.graph_title.setObjectName("graph_title")
        self.gridLayout_13.addWidget(self.graph_title, 1, 2, 1, 1)
        self.line_width = QtWidgets.QDoubleSpinBox(self.tPlotting)
        self.line_width.setDecimals(1)
        self.line_width.setMinimum(0.1)
        self.line_width.setMaximum(50.0)
        self.line_width.setProperty("value", 1.0)
        self.line_width.setObjectName("line_width")
        self.gridLayout_13.addWidget(self.line_width, 4, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tPlotting)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tPlotting)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tPlotting)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 5, 0, 1, 1)
        self.legend_spacing = QtWidgets.QSpinBox(self.tPlotting)
        self.legend_spacing.setMaximum(200)
        self.legend_spacing.setSingleStep(1)
        self.legend_spacing.setObjectName("legend_spacing")
        self.gridLayout_13.addWidget(self.legend_spacing, 5, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_13)
        self.gridLayout_14.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tPlotting, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRestoreDefaultSettings = QtWidgets.QPushButton(Dialog)
        self.btnRestoreDefaultSettings.setMinimumSize(QtCore.QSize(170, 0))
        self.btnRestoreDefaultSettings.setObjectName("btnRestoreDefaultSettings")
        self.horizontalLayout.addWidget(self.btnRestoreDefaultSettings)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.general_imp_delimiter)
        Dialog.setTabOrder(self.general_imp_delimiter, self.general_imp_decimal_sep)
        Dialog.setTabOrder(self.general_imp_decimal_sep, self.excel_imp_as_text)
        Dialog.setTabOrder(self.excel_imp_as_text, self.clip_imp_delimiter)
        Dialog.setTabOrder(self.clip_imp_delimiter, self.clip_imp_decimal_sep)
        Dialog.setTabOrder(self.clip_imp_decimal_sep, self.csv_exp_delimiter)
        Dialog.setTabOrder(self.csv_exp_delimiter, self.csv_exp_decimal_sep)
        Dialog.setTabOrder(self.csv_exp_decimal_sep, self.general_exp_delimiter)
        Dialog.setTabOrder(self.general_exp_delimiter, self.general_exp_decimal_sep)
        Dialog.setTabOrder(self.general_exp_decimal_sep, self.clip_exp_include_group_name)
        Dialog.setTabOrder(self.clip_exp_include_group_name, self.clip_exp_include_header)
        Dialog.setTabOrder(self.clip_exp_include_header, self.clip_exp_delimiter)
        Dialog.setTabOrder(self.clip_exp_delimiter, self.clip_exp_decimal_sep)
        Dialog.setTabOrder(self.clip_exp_decimal_sep, self.antialiasing)
        Dialog.setTabOrder(self.antialiasing, self.show_grid)
        Dialog.setTabOrder(self.show_grid, self.grid_alpha)
        Dialog.setTabOrder(self.grid_alpha, self.left_axis_label)
        Dialog.setTabOrder(self.left_axis_label, self.bottom_axis_label)
        Dialog.setTabOrder(self.bottom_axis_label, self.btnRestoreDefaultSettings)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Files"))
        self.label_11.setText(_translate("Dialog", "\\n - new line\n"
"\\t - tabulator"))
        self.label_3.setText(_translate("Dialog", "Delimiter"))
        self.label_7.setText(_translate("Dialog", "General (*.txt, etc.)"))
        self.label_4.setText(_translate("Dialog", "Decimal separator"))
        self.label_6.setText(_translate("Dialog", "DX file"))
        self.label_5.setText(_translate("Dialog", "CSV file"))
        self.groupBox_5.setTitle(_translate("Dialog", "DX file"))
        self.dx_import_spectra_name_from_filename.setText(_translate("Dialog", "Import spectra name\n"
"from filename"))
        self.rb_DX_import_from_title.setText(_translate("Dialog", "Import spectra name\n"
"from ##TITLE entry"))
        self.dx_if_title_is_empty_use_filename.setText(_translate("Dialog", "If ##TITLE is empty, use\n"
"spectra name from filename"))
        self.groupBox_6.setTitle(_translate("Dialog", "CSV and General files"))
        self.label.setText(_translate("Dialog", "If possible (for non-concatenated data),"))
        self.general_import_spectra_name_from_filename.setText(_translate("Dialog", "Import spectra name\n"
"from filename"))
        self.rb_general_import_from_header.setText(_translate("Dialog", "Import spectra name\n"
"from header"))
        self.general_if_header_is_empty_use_filename.setText(_translate("Dialog", "If header is empty, use\n"
"spectra name from filename"))
        self.groupBox_2.setTitle(_translate("Dialog", "Clipboard"))
        self.excel_imp_as_text.setText(_translate("Dialog", "Import data from MS Excel as text\n"
"(if checked, decimal precision will be lost)"))
        self.label_10.setText(_translate("Dialog", "Set how to import text data from clipboard (in order to retain compatibility with MS Excel/Origin, keep delimiter set as tabulator \\t, decimal separator is application specific)"))
        self.label_8.setText(_translate("Dialog", "Delimiter"))
        self.label_9.setText(_translate("Dialog", "Decimal separator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tImport), _translate("Dialog", "Import"))
        self.groupBox_4.setTitle(_translate("Dialog", "Clipboard"))
        self.label_18.setText(_translate("Dialog", "Set how to export text data to clipboard (in order to retain compatibility with MS Excel/Origin, keep delimiter set as tabulator \\t, decimal separator is application specific)"))
        self.clip_exp_include_group_name.setText(_translate("Dialog", "Include group name"))
        self.clip_exp_include_header.setText(_translate("Dialog", "Include header"))
        self.label_19.setText(_translate("Dialog", "Delimiter"))
        self.label_20.setText(_translate("Dialog", "Decimal separator"))
        self.groupBox_3.setTitle(_translate("Dialog", "Files"))
        self.label_17.setText(_translate("Dialog", "\\n - new line\n"
"\\t - tabulator"))
        self.files_exp_include_group_name.setText(_translate("Dialog", "Include group name"))
        self.files_exp_include_header.setText(_translate("Dialog", "Include header"))
        self.label_13.setText(_translate("Dialog", "Decimal separator"))
        self.label_15.setText(_translate("Dialog", "CSV file"))
        self.label_16.setText(_translate("Dialog", "General (*.txt, etc.)"))
        self.label_12.setText(_translate("Dialog", "Delimiter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tExport), _translate("Dialog", "Export"))
        self.antialiasing.setText(_translate("Dialog", "Antialiasing"))
        self.show_grid.setText(_translate("Dialog", "Show grid"))
        self.same_color_in_group.setText(_translate("Dialog", "Plot spectra with same color in groups"))
        self.different_line_style_among_groups.setText(_translate("Dialog", "Plot spectra with different line style among groups"))
        self.label_21.setText(_translate("Dialog", "Left axis label"))
        self.label_14.setText(_translate("Dialog", "Bottom axis label"))
        self.label_2.setText(_translate("Dialog", "Grid alpha"))
        self.label_22.setText(_translate("Dialog", "Graph title"))
        self.label_23.setText(_translate("Dialog", "Line width"))
        self.label_24.setText(_translate("Dialog", "Legend spacng"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tPlotting), _translate("Dialog", "Plotting"))
        self.btnRestoreDefaultSettings.setText(_translate("Dialog", "Restore Default Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
