# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widgets\Fit_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1374, 517)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.main_layout = QtWidgets.QGridLayout(Form)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 450))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbClass = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbClass.sizePolicy().hasHeightForWidth())
        self.cbClass.setSizePolicy(sizePolicy)
        self.cbClass.setObjectName("cbClass")
        self.gridLayout_3.addWidget(self.cbClass, 0, 1, 1, 1)
        self.cbModel = QtWidgets.QComboBox(self.groupBox)
        self.cbModel.setObjectName("cbModel")
        self.gridLayout_3.addWidget(self.cbModel, 1, 1, 1, 1)
        self.cbMethod = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMethod.sizePolicy().hasHeightForWidth())
        self.cbMethod.setSizePolicy(sizePolicy)
        self.cbMethod.setObjectName("cbMethod")
        self.gridLayout_3.addWidget(self.cbMethod, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.btnSimulateModel = QtWidgets.QPushButton(self.groupBox)
        self.btnSimulateModel.setCheckable(False)
        self.btnSimulateModel.setChecked(False)
        self.btnSimulateModel.setAutoRepeat(False)
        self.btnSimulateModel.setAutoDefault(False)
        self.btnSimulateModel.setObjectName("btnSimulateModel")
        self.verticalLayout_2.addWidget(self.btnSimulateModel)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(350, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 348, 282))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.glKinetics = QtWidgets.QGridLayout()
        self.glKinetics.setObjectName("glKinetics")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.glKinetics.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.glKinetics.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.glKinetics.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.glKinetics.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.glKinetics.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.glKinetics.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.glKinetics, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sbN = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbN.setMinimum(1)
        self.sbN.setMaximum(100)
        self.sbN.setObjectName("sbN")
        self.horizontalLayout.addWidget(self.sbN)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(37, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.cbRegressorS = QtWidgets.QComboBox(self.groupBox_3)
        self.cbRegressorS.setObjectName("cbRegressorS")
        self.horizontalLayout_2.addWidget(self.cbRegressorS)
        spacerItem3 = QtWidgets.QSpacerItem(37, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.cbRegressorC = QtWidgets.QComboBox(self.groupBox_3)
        self.cbRegressorC.setObjectName("cbRegressorC")
        self.horizontalLayout_2.addWidget(self.cbRegressorC)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbClosureConstraintC = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbClosureConstraintC.setObjectName("cbClosureConstraintC")
        self.horizontalLayout_5.addWidget(self.cbClosureConstraintC)
        self.txbClosureConstrValue = QtWidgets.QLineEdit(self.groupBox_3)
        self.txbClosureConstrValue.setObjectName("txbClosureConstrValue")
        self.horizontalLayout_5.addWidget(self.txbClosureConstrValue)
        spacerItem4 = QtWidgets.QSpacerItem(34, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.glSC_setup = QtWidgets.QGridLayout()
        self.glSC_setup.setObjectName("glSC_setup")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.glSC_setup.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.glSC_setup.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.glSC_setup.addWidget(self.label_17, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.glSC_setup.addWidget(self.label_15, 0, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.glSC_setup.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.glSC_setup.addWidget(self.label_10, 0, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.glSC_setup.addWidget(self.label_19, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.glSC_setup)
        spacerItem5 = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.sb_max_iter = QtWidgets.QSpinBox(self.groupBox_4)
        self.sb_max_iter.setMinimum(1)
        self.sb_max_iter.setMaximum(5000)
        self.sb_max_iter.setProperty("value", 10)
        self.sb_max_iter.setObjectName("sb_max_iter")
        self.verticalLayout_4.addWidget(self.sb_max_iter)
        self.btnFit = QtWidgets.QPushButton(self.groupBox_4)
        self.btnFit.setCheckable(False)
        self.btnFit.setChecked(False)
        self.btnFit.setAutoRepeat(False)
        self.btnFit.setAutoDefault(False)
        self.btnFit.setObjectName("btnFit")
        self.verticalLayout_4.addWidget(self.btnFit)
        self.btnOneIt = QtWidgets.QPushButton(self.groupBox_4)
        self.btnOneIt.setCheckable(False)
        self.btnOneIt.setChecked(False)
        self.btnOneIt.setAutoRepeat(False)
        self.btnOneIt.setAutoDefault(False)
        self.btnOneIt.setObjectName("btnOneIt")
        self.verticalLayout_4.addWidget(self.btnOneIt)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.btnST_calc = QtWidgets.QPushButton(self.groupBox_4)
        self.btnST_calc.setCheckable(False)
        self.btnST_calc.setChecked(False)
        self.btnST_calc.setAutoRepeat(False)
        self.btnST_calc.setAutoDefault(False)
        self.btnST_calc.setObjectName("btnST_calc")
        self.verticalLayout_4.addWidget(self.btnST_calc)
        self.btnC_calc = QtWidgets.QPushButton(self.groupBox_4)
        self.btnC_calc.setCheckable(False)
        self.btnC_calc.setChecked(False)
        self.btnC_calc.setAutoRepeat(False)
        self.btnC_calc.setAutoDefault(False)
        self.btnC_calc.setObjectName("btnC_calc")
        self.verticalLayout_4.addWidget(self.btnC_calc)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.main_layout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Kinetics (Hard modeling - C matrix constraints)"))
        self.label_22.setText(_translate("Form", "Model:"))
        self.label_9.setText(_translate("Form", "Minimizing algorithm:"))
        self.label_2.setText(_translate("Form", "Class:"))
        self.btnSimulateModel.setText(_translate("Form", "Simulate for current params"))
        self.label_7.setText(_translate("Form", "Fixed"))
        self.label_3.setText(_translate("Form", "Param"))
        self.label_8.setText(_translate("Form", "Error"))
        self.label_6.setText(_translate("Form", "Upper\n"
"bound"))
        self.label_4.setText(_translate("Form", "Lower\n"
"bound"))
        self.label_5.setText(_translate("Form", "<= Value <="))
        self.groupBox_3.setTitle(_translate("Form", "Spectra (S) and concentration (C) matrices setup"))
        self.label.setText(_translate("Form", "Number of compartments:"))
        self.label_13.setText(_translate("Form", "                --- S matrix ---"))
        self.label_21.setText(_translate("Form", "--- C matrix ---                "))
        self.label_14.setText(_translate("Form", "Regressor:   "))
        self.cbClosureConstraintC.setText(_translate("Form", "Global closure constraint for C, value:"))
        self.txbClosureConstrValue.setText(_translate("Form", "1"))
        self.label_11.setText(_translate("Form", "Component\n"
"(column of C and S)"))
        self.label_16.setText(_translate("Form", "Fixed"))
        self.label_17.setText(_translate("Form", "Conc. profile"))
        self.label_15.setText(_translate("Form", "Constrain (MCR)"))
        self.label_18.setText(_translate("Form", "Constrain (MCR)"))
        self.label_10.setText(_translate("Form", "Fixed"))
        self.label_19.setText(_translate("Form", "||"))
        self.groupBox_4.setTitle(_translate("Form", "Fit, D = CS^T"))
        self.label_12.setText(_translate("Form", "Max iterations (MCR routine):"))
        self.btnFit.setText(_translate("Form", "Fit"))
        self.btnOneIt.setText(_translate("Form", "One iteration"))
        self.btnST_calc.setText(_translate("Form", "<- ST (MCR half iter.)"))
        self.btnC_calc.setText(_translate("Form", "C (MCR half iter.) ->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
